#!/bin/bash
# Cron wrapper: quarterly memory audit (Obsidian stats + report stub)
set -euo pipefail
VAULT="$HOME/Obsidian/Penelopi"
AUDIT_DIR="$VAULT"
YEAR=$(date +%Y)
QUARTER=$(( (10#$(date +%m) - 1) / 3 + 1 ))
REPORT="$AUDIT_DIR/audit-${YEAR}-Q${QUARTER}.md"

MEMORY="$VAULT/MEMORY.md"
MEMORY_LINES=$([ -f "$MEMORY" ] && wc -l < "$MEMORY" | tr -d ' ' || echo 0)
DAILY_TOTAL=$(find "$VAULT/Daily" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
PROJECTS=$(find "$VAULT/Projects" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

cat > "$REPORT" <<EOF
# Quarterly Memory Audit — ${YEAR} Q${QUARTER}

## Automated scan ($(date +%Y-%m-%d))

| Metric | Value |
|--------|-------|
| Daily notes total | $DAILY_TOTAL |
| Project files | $PROJECTS |
| MEMORY.md | $([ -f "$MEMORY" ] && echo "exists (${MEMORY_LINES} lines)" || echo "MISSING") |

## Manual deep-clean checklist

1. Full read-through of MEMORY.md — verify facts >90 days old
2. Cross-check Projects/ against reality
3. Archive obsolete Lessons Learned
4. Flag entries needing Okeito verification

Generated by scripts/cron-quarterly-memory.sh
EOF

# Rich formatted summary for Telegram
echo "🧠 *Quarterly Memory Audit*

📊 *Stats for ${YEAR} Q${QUARTER}*
• Daily notes total: \`$DAILY_TOTAL\`
• Project files: \`$PROJECTS\`
• MEMORY.md: \`${MEMORY_LINES} lines\`

⚡ *Deep-Clean Checklist*
• Verify facts >90 days old
• Cross-check Projects/ against reality
• Archive obsolete Lessons Learned
• Flag entries needing Okeito verification

📁 Report: \`$REPORT\`"
