#!/bin/bash
# Cron wrapper: weekly memory maintenance (Obsidian, no agent)
set -euo pipefail
VAULT="$HOME/Obsidian/Penelopi"
REPORT_DIR="$VAULT/maintenance"
DATE=$(date +%Y-%m-%d)
REPORT="$REPORT_DIR/${DATE}-weekly.md"
mkdir -p "$REPORT_DIR"

MEMORY="$VAULT/MEMORY.md"
DAILY_COUNT=$(find "$VAULT/Daily" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
OLD_DAILY=$(find "$VAULT/Daily" -name "*.md" -mtime +90 2>/dev/null | wc -l | tr -d ' ')
PROJECTS=$(find "$VAULT/Projects" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

cat > "$REPORT" <<EOF
# Weekly Memory Maintenance — $DATE

## Stats
- Daily notes: $DAILY_COUNT files
- Daily notes >90 days: $OLD_DAILY (candidate archive)
- Project files: $PROJECTS
- MEMORY.md: $([ -f "$MEMORY" ] && echo "exists ($(wc -l < "$MEMORY" | tr -d ' ') lines)" || echo "MISSING")

## Actions needed
- Review MEMORY.md for entries >30 days without verification
- Archive Daily/ notes >90 days if confirmed stale
- Update PROJECTS/ status fields

Generated by scripts/cron-weekly-memory.sh
EOF

echo "Memory maintenance report: $REPORT"
cat "$REPORT"
