#!/bin/bash
# Cron wrapper: monthly memory distillation (Obsidian stats + report stub)
set -euo pipefail
VAULT="$HOME/Obsidian/Penelopi"
REPORT_DIR="$VAULT/maintenance"
DATE=$(date +%Y-%m-%d)
MONTH=$(date +%Y-%m)
REPORT="$REPORT_DIR/${DATE}-monthly.md"
mkdir -p "$REPORT_DIR"

MEMORY="$VAULT/MEMORY.md"
DAILY_THIS_MONTH=$(find "$VAULT/Daily" -name "*.md" -newermt "$(date +%Y-%m-01)" 2>/dev/null | wc -l | tr -d ' ')
PROJECTS=$(find "$VAULT/Projects" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
MEMORY_LINES=$([ -f "$MEMORY" ] && wc -l < "$MEMORY" | tr -d ' ' || echo 0)

cat > "$REPORT" <<EOF
# Monthly Memory Distillation — $MONTH

## Automated scan ($DATE)

| Metric | Value |
|--------|-------|
| Daily notes this month | $DAILY_THIS_MONTH |
| Project files | $PROJECTS |
| MEMORY.md lines | $MEMORY_LINES |

## Manual follow-up (Okeito / main session)

1. Read Daily/ notes from past month — extract decisions worth keeping
2. Update MEMORY.md with distilled insights
3. Update Projects/ status fields
4. Archive dead projects

Generated by scripts/cron-monthly-memory.sh
EOF

# Rich formatted summary for Telegram
echo "🧠 *Monthly Memory Distillation*

📊 *Stats for $MONTH*
• Daily notes this month: \`$DAILY_THIS_MONTH\`
• Project files: \`$PROJECTS\`
• MEMORY.md lines: \`$MEMORY_LINES\`

⚡ *Actions*
• Read Daily/ notes from past month
• Update MEMORY.md with distilled insights
• Update Projects/ status fields
• Archive dead projects

📁 Report: \`$REPORT\`"
